### ISSUE TITLE
Error: Could not upload contract: Error: {"code":12,"message":"Not Implemented","details":[]} (HTTP 501)

### ISSUE THREAD

**Issue by ChristianOConnor** [floAr/FigmentLearn-FromZeroToYourFirstSecretNFT#1]
I followed the YouTube tutorial nearly perfectly but when I get to `node contract/deploy.nft` I get this:  
```
Uploading contract
Error: Could not upload contract: Error: {"code":12,"message":"Not Implemented","details":[]} (HTTP 501)
    at /Users/<myusername>/Desktop/Dev/ScratchSpace/secret-nft-first/contract/deploy-nft.js:65:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/Users/<myusername>/Desktop/Dev/ScratchSpace/secret-nft-first/contract/deploy-nft.js:64:25)
<myusername>@<mycomputername> secret-nft-first % 
```  

What do you think is causing this problem? One thing I thought might be a problem is that my `VITE_SECRET_REST_URL` looks like this (replacing <API KEY HERE> with my API key of course) `'https://secret-pulsar-2--lcd--full.datahub.figment.io/apikey/<API KEY HERE>/blocks/latest'`. This is different than yours because mine has a `/blocks/latest` appended to the end and yours doesn't but that's only because I'm following `https://datahub.figment.io/` instructions on how to implement their rest url into my project.  

I even filled out the `initMsg` const correctly:  
```
  const initMsg = {
    /// name of token contract
    name: "NFTTestOne",
    /// token contract symbol
    symbol: "NTTO",
    /// entropy used for prng seed
    entropy: "asdf6T",
    /// optional privacy configuration for the contract
    config: {
      public_owner: true,
    },
  };
```  

One other issue could be that I used enigmampc/secret-contract-optimizer:1.0.7 instead of enigmampc/secret-contract-optimizer:1.0.5? 1.0.5 gave me errors.

**Comment by floAr** [comment]
Hey @ChristianOConnor, there are parts that might be a bit outdated right now, but looking at it right now I would assume that the error is with your Endpoint. 
`/blocks/latest` is already a specific endpoint, whereas the `VITE_SECRET_REST_URL ` is supposed to be the 'root' of the api. So that should not contain `/block/latest`

**Comment by ChristianOConnor** [comment]
> Hey @ChristianOConnor, there are parts that might be a bit outdated right now, but looking at it right now I would assume that the error is with your Endpoint. `/blocks/latest` is already a specific endpoint, whereas the `VITE_SECRET_REST_URL ` is supposed to be the 'root' of the api. So that should not contain `/block/latest`

Thanks that fixed it!
